#!/bin/bash

# Symlink ruby 1.9.1 into our vhost folder and setup our $PATH so that we use
# it as ruby, necessary to make bundler et all install the right gems
if [ ! -e ../bin/ruby ]; then
    echo "Symlinking ruby1.9.1 as ../bin/ruby"
    mkdir -p ../bin
    ln -sf /usr/bin/ruby1.9.1 ../bin/ruby
fi
BIN_DIR="`(cd ../bin && pwd)`"
export PATH="$BIN_DIR:$PATH"
echo "Ruby version is now: `../bin/ruby -v`"

if [ -e config/httpd.conf ] && egrep -q '^\s*RackEnv\s*production' config/httpd.conf
then
    export RAILS_ENV=production
else
    export RAILS_ENV=development
fi

bundle install --deployment

# only attempt to load the schema if there are no previous migrations
db_version=`bundle exec rake db:version | grep 'Current version: '`
if [[ $db_version == "Current version: 0" ]]
then
  echo "first run, loading db schema..."
  bundle exec rake db:schema:load
else
  echo "existing db detected, skipping schema:load task"
fi

bundle exec rake db:migrate

if [ "$RAILS_ENV" = production ]
then
    bundle exec rake assets:precompile
fi